# Generated by Django 3.0.3 on 2020-02-28 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ph', models.CharField(max_length=100)),
                ('birthdate', models.DateTimeField()),
                ('specilized_in', models.CharField(max_length=100)),
                ('hospitalname', models.CharField(max_length=100)),
                ('hospitaladdress', models.CharField(max_length=100)),
                ('hospitalstate', models.CharField(max_length=100)),
                ('hospitaldistrict', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('Morning(7am-1pm)', 'Morning(7am-1pm)'), ('Afternoon(1pm to 7pm)', 'Afternoon(1pm to 7pm)')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
